### PR TITLE
added 4 blocked servers

### PR DESCRIPTION
**Pull request by Lergin**

### CODE REVIEW

**Comment by Lergin** [comment]
with this and #9 once again all servers are identified

**Comment by Chnkr** [comment]
Thanks for your contribution! Manually merged this in `d5cf22f19143de25064e0119c7f4613ae269361d`

**Comment by kamcio96** [comment]
@Chnkr Why you don't use auto merge?

**Comment by Chnkr** [comment]
@kamcio96 The backend is automatically building the `blockedservers` file based on the dict in `support/dictionary` the backend is bascially doing a `git add .` every 5 minutes.

**Pull request closed without merging**
